### PR TITLE
Create February-2023-image-minutes.md

### PR DESCRIPTION
**Pull request by uschille**

### CODE REVIEW

**Review by joshmoore — APPROVED** [review]
Thanks for the notes. :+1: from me.

Only question I have is if the planned meeting time shift is intentional. If so, I'll adjust the next calendar entry (though I've just updated permissions so all CAC members can modify the events)

**Comment by uschille** [comment]
> Only question I have is if the planned meeting time shift is intentional. If so, I'll adjust the next calendar entry (though I've just updated permissions so all CAC members can modify the events)

That's probably my mistake, I'll double check - I am on travel across time zones - CET last week, PST this week, and back to EST next week :dizzy:

**Comment by joshmoore** [comment]
Heh :smile: I definitely understand that feeling.

**Comment by joshmoore** [comment]
Screenshot 2023-03-07 at 14 14 36
That matches what's in my calendar. Thanks, @uschille :+1:

**Pull request merged**
